### ISSUE TITLE
[Feature] Full control over blocking click, drag and zoom

### ISSUE THREAD

**Issue by degroote22** [mariusandra/pigeon-maps#18]
Right now you can add classes to markers no prevent clicking and dragging over them but this insufficient for my use case.
I have two cases where I need to set globally if the map should be clickable, draggable and zoomable.
The first one is when the map has an overlay over it, something like a modal or popup.
The second use case is displaying static but dynamic-generated maps.

@mariusandra would you mind adding these 3 props to the API? I'll come up with a PR for this ASAP if so.

I'm thinking about using something like
```javascript
<Map
  blockClick={true}
  blockDrag={true}
  blockZoom={true}
/>
```

**Comment by mariusandra** [comment]
Hey, for the first point, the real solution is to use [`document.elementFromPoint`](http://caniuse.com/#search=document.elementFromPoint) and check if the click landed on something that's a child of the map, or something else. I released `0.8.2` with this fix.

Here's a demo: https://youtu.be/Nb_wtx2cg-0

For the second use case, I would call them something like this:

```
<Map
    clickable 
    draggable
    zoomable
    scrollable={false}
/>
```

.. but I'm not sure which events should be there, as there are separate touch and mouse events that exist.

I use google map's `scrollwheel = false` myself quite often, so I understand the need.

**Comment by degroote22** [comment]
The point of using blockFoo naming is not "breaking compatibility" with the current API.
I don't think it would be good to tell, imperatively, that the map should be clickable, draggable, zoomable and scrollable. It should come by default.

And since it's hard to controll what events should be blocked whenever something happens what do you think of 
```javascript
<Map
  static={true}
/>
```

```javascript
<Map
  static
/>
```

**Comment by mariusandra** [comment]
Hey, in my example all those flags would be `true` by default and it would be up to the user to set them to false to disable them. So nothing breaks with the current API.

I think `clickable={false}` reads better than `blockClick={true}`, but of course just `<Map blockClick />` is clear as well. The problem comes when you have a dynamic variable setting the state, as in: `<Map blockClick={!clicksEnabled} />`. In that case it becomes hard to intuitively grasp the code due to the double negative.

Looking at what others (google maps, leaflet) do, it appears the convention is to specify things like 
[`scrollWheel: true`](https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapOptions), [`draggable: true`](http://leafletjs.com/reference-1.0.3.html#marker-draggable), [`keyboard: true`](http://leafletjs.com/reference-1.0.3.html#map-keyboard), [`touchZoom: true`](http://leafletjs.com/reference-1.0.3.html#map-touchzoom), etc.

So I would go for this way.

**Comment by lorem--ipsum** [comment]
Alternatively, wouldn't `pointer-events: none;` solve the problem ?

**Comment by degroote22** [comment]
I'm sorry for the delay. I ended up getting lost on this and using a transparent overlay over the map solves the issue.
If this is requested by more use cases then I'll work on a pr.
I'm closing this.
